apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs490-project
spec:
  destination:
    namespace: cs490-project
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/davidmcnamee/cs490-project.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
