apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: static-analysis-task
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  steps:
  - name: black
    image: davidmc1/cs490-project:latest
    command:
      - sh
      - -c
      - |
        poetry install
        poetry run pylint api
        if [ $? -ne 0 ]; then exit 1; fi
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: static-analysis-task-run-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  taskRef:
    name: static-analysis-task
