apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: davidmc1/cs490-project:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: DATABASE_URL
        - name: FLASK_RUN_HOST
          value: '0.0.0.0'
        - name: FLASK_APP
          value: api/app.py
        - name: FLASK_ENV
          value: development 
        - name: FLASK_DEBUG
          value: "1"

