name: pull-request-ci

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: davidmc1
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: davidmc1/cs490-project:latest
          context: "{{defaultContext}}:src"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: cd src && poetry install && poetry run prisma generate
      - name: Lint
        run: cd src && poetry run pylint api

